name 'hw_cookbooks_bag_config'
maintainer       'Chris Roberts'
maintainer_email 'chrisroberts.code@gmail.com'
license          'Apache-2.0'
description      'Provides helpers for optional data bag configuration'
version          '2.0.2'
